# Generated by Django 4.2.1 on 2023-06-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
