# Generated by Django 4.2.1 on 2023-07-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_account_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_name',
        ),
    ]
