# Generated by Django 4.2.1 on 2023-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_account_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profiles/'),
        ),
    ]
