# Generated by Django 4.2.1 on 2023-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='profile.jpeg/', upload_to='profiles/', verbose_name='profile'),
        ),
    ]
