# Generated by Django 4.2.1 on 2023-06-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_caption', models.CharField(max_length=200)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_acoount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_caption', models.CharField(max_length=200)),
                ('comment_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.account')),
            ],
        ),
    ]
