# Generated by Django 4.2.1 on 2023-06-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_acoount',
            new_name='post_account',
        ),
    ]
