# Generated by Django 4.2.1 on 2023-07-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_account_user_name'),
        ('posts', '0008_post_when_posted_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_account', to='authenticate.account'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='authenticate.account'),
        ),
    ]
