# Generated by Django 4.2.1 on 2023-07-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_account_user_name'),
        ('posts', '0009_alter_post_post_account_remove_post_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_account', to='authenticate.account'),
        ),
    ]
