# Generated by Django 4.2.1 on 2023-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_account_profile_pic'),
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to='authenticate.account'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to='authenticate.account'),
        ),
    ]
