# Generated by Django 4.2.1 on 2023-08-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_account_profile_pic'),
        ('messages_api', '0002_remove_chat_receiver_remove_chat_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(null=True, related_name='receiver', to='authenticate.account'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='authenticate.account'),
        ),
    ]
