# Generated by Django 4.2.1 on 2023-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_account_profile_pic'),
        ('messages_api', '0003_alter_chat_receiver_remove_chat_sender_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to='authenticate.account'),
        ),
    ]
