# Generated by Django 4.2.1 on 2023-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0005_remove_chat_receiver_chat_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_content',
        ),
        migrations.AddField(
            model_name='chat',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
