# Generated by Django 4.2.1 on 2023-08-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_account_profile_pic'),
        ('messages_api', '0006_remove_chat_message_content_chat_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='authenticate.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='authenticate.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sent',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('seen', models.BooleanField(default=False)),
                ('sent', models.TimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='messages_api.contact')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='authenticate.account')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='messages_api.message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to='messages_api.contact'),
        ),
    ]
